# -*- coding: utf-8 -*-
"""after_xl_scr

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b3VXkHSUL8qaZE8LvrnmW17Nh3gh3TGN
"""

from openpyxl import load_workbook
import streamlit as st
from io import BytesIO

def xl_data_get
  after_xl = st.file_uploder("アフター申請書エクセルをアップロードしてください")

if after_xl is not None:
  file_mime = after_xl.type

  if file_mime == `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`:
    file = BytesIO(after_xl.getvalue())
    wb = load_workbook(filename=file)
    sheet = wb.active
    st.write(f"Sheet title: {sheet.title}")

  else:
    st.write("エクセルファイル(.xlsx)をアップロードしてください")
    st.stop()